pngcrush: malformed or missing argument
In pngcrush 1.7.71 wrong parameters:

Error: pngcrush: malformed or missing argument
-max  needs a value

Error: Ignoring invalid method: 0
-p needs a value between 1 and 9